In [1]:
import pandas as pd
import numpy as np
import csv
import re

In [2]:
test_file_plate_2_1 = "C:\\Users\\Bartek\\OneDrive\\Documents\\Programming\\Python\\Test data\\Protein titration LissamineFA_22267.csv"
test_file_plate_2_2 = "C:\\Users\\Bartek\\OneDrive\\Documents\\Programming\\Python\\Test data\\Protein titration LissamineFA_22741.csv"
test_file_list_A = "C:\\Users\\Bartek\\OneDrive\\Documents\\Programming\\Python\\Test data\\Outputfiles\\csv\\listA.csv"
test_file_repeat_read_plate_1 = "C:\\Users\\Bartek\\OneDrive\\Documents\\Programming\\Python\\Test data\\Outputfiles\\csv\\repeat read_plate1.csv"
test_file_repeat_read_plate_2 = "C:\\Users\\Bartek\\OneDrive\\Documents\\Programming\\Python\\Test data\\Outputfiles\\csv\\repeat read_plate2.csv"

In [3]:
reader = csv.reader(open(test_file_repeat_read_plate_2, 'r'), delimiter=',') 
    
all_data = [] 
dfs = {}
counter = 0

# Create a list of lists with all data in the csv file
for row in reader:
    all_data.append(row)   

# Find the total noumber of rows in the file
for index, item in enumerate(all_data):
    if item != [] and re.search(r"Exported with EnVision Workstation", item[0]) != None:   # Blank rows cannot be indexed 
        total_lines = index + 1  

# Find the data
for index, item in enumerate(all_data):
    if item != [] and re.findall(r"Plate information", item[0]) == ['Plate information'] and re.search(r'Results for', all_data[index + 9][0]) != None:
        skiprows = index + 10   # Set the skiprows parameter
        end_of_data = 0
        
        # find the index of the first blank row after the data table
        while end_of_data == 0:   
            for index, item in enumerate(all_data):
                if item == [] and index > skiprows:  
                    end_of_data = end_of_data + index
                    break
                    
        skipfooter = total_lines - end_of_data   # calucalte the skipfooter parameter
        
        # extract data into pandas df and add it to a dictionary
        df = pd.read_csv(test_file_repeat_read_plate_2, sep=',', index_col=0, engine='python', skiprows=skiprows, skipfooter=skipfooter, encoding='utf-8')
        dfs[counter] = df
        
        counter = counter + 1

In [4]:
len(dfs)

4

In [5]:
dfs[0]

,01,02,03,04,05,06,07,08,09,10,...,16,17,18,19,20,21,22,23,24,Unnamed: 25
A,18781491.0,27318000.0,15885300.0,21036054.0,22823211.0,19070359.0,6854639.0,15348069.0,9178898.0,5116587.0,...,10110194.0,14236276.0,22615847.0,12174025.0,7747257.0,14475328.0,6088345.0,17233582.0,11476180.0,NaN
B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
C,17682352.0,25542206.0,28037904.0,12162314.0,17808198.0,9662208.0,21511273.0,10788239.0,8096173.0,19002255.0,...,3498738.0,8781437.0,6078456.0,13754476.0,22041950.0,18250237.0,17730987.0,16866924.0,11972287.0,NaN
D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E,34003407.0,9165626.0,14432167.0,20991721.0,26150693.0,13621214.0,13509098.0,19824875.0,13174169.0,18269822.0,...,5660147.0,24534945.0,8320162.0,26730272.0,41065444.0,8805493.0,20776813.0,10280069.0,11638872.0,NaN
F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
G,30380651.0,5701796.0,7842883.0,17906039.0,21431849.0,44320736.0,16991191.0,16541170.0,12761778.0,10857959.0,...,19040502.0,6928443.0,18090316.0,17215031.0,22431941.0,11683990.0,5346228.0,16190696.0,15246229.0,NaN
H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
I,11522470.0,11487932.0,12756990.0,7610040.0,3799031.0,16271071.0,15723197.0,17646782.0,5127155.0,11517274.0,...,15090730.0,18762302.0,15171632.0,3632708.0,15982624.0,14974967.0,12431844.0,9353416.0,10465245.0,NaN
J,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
K,10889550.0,9973788.0,14854795.0,14909991.0,15524625.0,17754357.0,12981814.0,7814958.0,27455678.0,10863825.0,...,13819538.0,6299007.0,16290404.0,7598091.0,25057561.0,10428058.0,8041741.0,13500922.0,13085743.0,NaN
L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
O,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
dfs[3]

,01,02,03,04,05,06,07,08,09,10,...,16,17,18,19,20,21,22,23,24,Unnamed: 25
A,20296635.0,29313577.0,18404541.0,23410696.0,24606892.0,21274689.0,8495224.0,16904527.0,10804345.0,6566435.0,...,11709061.0,15664508.0,24643755.0,14231749.0,9274197.0,16414670.0,7839955.0,19557852.0,13688881.0,NaN
B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
C,20192899.0,27736731.0,30455034.0,14187352.0,19881889.0,11524185.0,23104185.0,12261676.0,9781943.0,21492979.0,...,4777858.0,10516543.0,7648376.0,15522464.0,24153243.0,20163553.0,19065615.0,18608311.0,13581258.0,NaN
D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E,34736780.0,10921991.0,17059766.0,23482203.0,29164636.0,15591021.0,15422070.0,22293624.0,15172438.0,20586313.0,...,7066824.0,26228846.0,9683224.0,28558875.0,39801950.0,10340556.0,21993450.0,11651594.0,13086110.0,NaN
F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
G,32492002.0,7781177.0,9842146.0,19766097.0,23992170.0,44790693.0,19321716.0,18772869.0,14948871.0,12230175.0,...,20515581.0,8211623.0,19448321.0,18479107.0,23280556.0,12825141.0,6552028.0,17817212.0,16556844.0,NaN
H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
I,13494542.0,14217969.0,15026758.0,10060114.0,5182467.0,18576110.0,18215789.0,20466227.0,6680187.0,14067046.0,...,16252184.0,20318939.0,16764768.0,4340690.0,17626852.0,15843442.0,12753116.0,10411745.0,11456917.0,NaN
J,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
K,12823080.0,12406701.0,16811383.0,16836619.0,17817310.0,20331783.0,14546248.0,9508711.0,30539299.0,12906639.0,...,15260843.0,6721286.0,17091864.0,8508588.0,26424284.0,11337218.0,8801218.0,14211489.0,13838929.0,NaN
L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
O,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN